# Generated by Django 3.2.10 on 2021-12-18 22:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=ckeditor.fields.RichTextField(max_length=255),
        ),
    ]
